const CONNECTION = {
	UPDATE: 'UPDATE',
	REMOVE: 'REMOVE'
}

const ROOM = {
	JOIN: "JOIN",
	LEAVE: "LEAVE",
	CREATE: "CREATE"
}

const GAME = {
	MOVE_PIECE: "MOVE_PIECE"
}

const REQUEST = {
	ROOMS: "ROOMS",
	ROOM_INFO: "ROOM_INFO",
	ROOM_CONFIG: "ROOM_CONFIG",
}

module.exports = {
	CLIENT_CONNECTION: CONNECTION,
	CLIENT_ROOM: ROOM,
	CLIENT_GAME: GAME,
	CLIENT_REQUEST: REQUEST
}