// shared between client and server

const ROOM_SUCCESS = {
	CLIENT_JOINED_ROOM: "JOIN",
	CLIENT_LEFT_ROOM: "LEAVE",
	CLIENT_MOVE_PIECE: "MOVE_PIECE",
	CLIENT_CREATE_ROOM: "CREATE"
}

const ROOM_ERROR = {
	CLIENT_JOIN: "JOIN",
	CLIENT_LEAVE: "LEAVE",
	CLIENT_MOVE_PIECE: "MOVE_PIECE",
	CLIENT_CREATE_ROOM: "CREATE",
}

const REQUEST_SUCCESS = {
	CLIENT_REQUEST_ROOMS: "ROOMS",
	CLIENT_REQUEST_ROOM: "ROOM",
	CLIENT_REQUEST_ROOM_CONFIG: 'ROOM_CONFIG',
}

const REQUEST_ERROR = {
	CLIENT_REQUEST_ROOMS: "ROOMS_ERROR",
	CLIENT_REQUEST_ROOM: "ROOM_ERROR",
	CLIENT_REQUEST_ROOM_CONFIG: 'ROOM_CONFIG',
}

module.exports = {
	SERVER_ROOM_SUCCESS: ROOM_SUCCESS,
	SERVER_ROOM_ERROR: ROOM_ERROR,
	SERVER_REQUEST_SUCCESS: REQUEST_SUCCESS,
	SERVER_REQUEST_ERROR: REQUEST_ERROR,
}