const CONNECTION_EVENT_TYPES = {
	ADD_CONNECTION: "ADD_CONNECTION",
	REMOVE_CONNECTION: "REMOVE_CONNECTION"
}

const ROOM_EVENT_TYPES = {
	CREATE_ROOM: "CREATE_ROOM",
	JOIN_ROOM: "JOIN_ROOM"
}

module.exports = {
	CONNECTION_EVENT_TYPES: CONNECTION_EVENT_TYPES,
	ROOM_EVENT_TYPES: ROOM_EVENT_TYPES
}